### ISSUE TITLE
Pass back results for programmatically reading an issue obtained from the github API to our caller

### ISSUE THREAD

**Issue by saraf** [CollaboRateMgmt/CollaboRate#5]
Given:
Results received from GitHub API
Information about how our caller wants the information (callback, promise, return value .... ) 

Convey the result of the API call to the caller.

Parent issue: #2

**Comment by sohrabsaran** [comment]
see comment in parent

**Comment by CollaboRateMgmt** [comment]
Unassigning, as rework is ok with me. Note that the description must ideally include the info in the summary as well.

**Comment by sohrabsaran** [comment]
Does this task specify the creation of a function? No

  Is this task a 'requirement', or is it a 'simple use case'?  requirement

   First subtask 
  Summary 
 How to pass back results for programmatically reading an issue obtained from the github API to our caller, from the synchronization respective
 
Description 
 Pass back results for programmatically reading an issue obtained from the github API to our caller.
Given:
Results received from GitHub API
Information about how our caller wants the information (callback, promise, return value .... ) ...we ideally want to have the information as a return value of a synchronous function call.
 
  

 Second subtask 
  Summary 
 Use the values of the issues read from GitHub to create tools that fulfil the goal of the CollaboRate project.
 
Description 
 Given a repository, and credentials for accessing the repository, use the values of the issues read from GitHub to create tools that fulfil the goal of the CollaboRate project. These tools will provide the following:
1. An advanced view of the data to GitHub users e.g. viewing the defects sorted by various categories including priority.  
2. We can also read code or pseudo-code embedded in issue comments and auto-generate the project codebase.
3. Have auto-validations based on NLP AI techniques. A bot will then update the github issues with messages accordingly. Note that editing or creating issues is out of the scope of this task.  

Non-crowd information related to implementation: To popularize this client-side tool and attract sponsors/investors, we will host this application using github.io, similar to or in addition to the CollaboRate online tool.

**Comment by sohrabsaran** [comment]
I will create the child tasks once the work breakdown given above is reviewed and approved.

**Comment by sohrabsaran** [comment]
By Aalhad: no comments

**Comment by sohrabsaran** [comment]
Child tasks created hence closing
